// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwkacvppxzillilgigrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3a2FjdnBweHppbGxpbGdpZ3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3ODY0ODQsImV4cCI6MjA5MDM2MjQ4NH0.BN0A8v2re3vtUQOidjL8MUld67FQEEToVIVA02kGv4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});